// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: shared/source_node.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SourceNode defines a node pointing the a source and children of the source for a given post
type SourceNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Source is the source of this tree node
	Source *Source `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Children are the
	Children []*Source `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *SourceNode) Reset() {
	*x = SourceNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_source_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceNode) ProtoMessage() {}

func (x *SourceNode) ProtoReflect() protoreflect.Message {
	mi := &file_shared_source_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceNode.ProtoReflect.Descriptor instead.
func (*SourceNode) Descriptor() ([]byte, []int) {
	return file_shared_source_node_proto_rawDescGZIP(), []int{0}
}

func (x *SourceNode) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SourceNode) GetChildren() []*Source {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_shared_source_node_proto protoreflect.FileDescriptor

var file_shared_source_node_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x72, 0x63, 0x61,
	0x62, 0x6c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x1a, 0x13, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e,
	0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73,
	0x72, 0x63, 0x61, 0x62, 0x6c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x73, 0x72, 0x63, 0x61, 0x62, 0x6c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x42, 0x21,
	0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x72, 0x63,
	0x61, 0x62, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_source_node_proto_rawDescOnce sync.Once
	file_shared_source_node_proto_rawDescData = file_shared_source_node_proto_rawDesc
)

func file_shared_source_node_proto_rawDescGZIP() []byte {
	file_shared_source_node_proto_rawDescOnce.Do(func() {
		file_shared_source_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_source_node_proto_rawDescData)
	})
	return file_shared_source_node_proto_rawDescData
}

var file_shared_source_node_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_source_node_proto_goTypes = []interface{}{
	(*SourceNode)(nil), // 0: srcabl.shared.SourceNode
	(*Source)(nil),     // 1: srcabl.shared.Source
}
var file_shared_source_node_proto_depIdxs = []int32{
	1, // 0: srcabl.shared.SourceNode.source:type_name -> srcabl.shared.Source
	1, // 1: srcabl.shared.SourceNode.children:type_name -> srcabl.shared.Source
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_source_node_proto_init() }
func file_shared_source_node_proto_init() {
	if File_shared_source_node_proto != nil {
		return
	}
	file_shared_source_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_shared_source_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_source_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_source_node_proto_goTypes,
		DependencyIndexes: file_shared_source_node_proto_depIdxs,
		MessageInfos:      file_shared_source_node_proto_msgTypes,
	}.Build()
	File_shared_source_node_proto = out.File
	file_shared_source_node_proto_rawDesc = nil
	file_shared_source_node_proto_goTypes = nil
	file_shared_source_node_proto_depIdxs = nil
}
